import { createTheme, createThemeContract } from "@vanilla-extract/css";

/** Defines the shared responsive breakpoints used by Sprinkles and local styles. */
export const breakpoints = { tablet: "screen and (min-width: 850px)" };

/** Defines the semantic design tokens shared by the Signal interface. */
export const vars = createThemeContract({
  color: {
    canvas: null,
    surface: null,
    surfaceRaised: null,
    input: null,
    text: null,
    ink: null,
    muted: null,
    accent: null,
    danger: null,
    border: null,
    borderStrong: null,
    overlay: null,
  },
  font: { sans: null, mono: null },
  fontSize: {
    xs: null,
    sm: null,
    body: null,
    base: null,
    medium: null,
    large: null,
    display: null,
    score: null,
  },
  fontWeight: { medium: null, bold: null, extraBold: null },
  lineHeight: { tight: null, body: null, relaxed: null },
  letterSpacing: { label: null, title: null, card: null, brand: null },
  radius: { sm: null, md: null, lg: null, xl: null, pill: null },
  space: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
  },
  size: {
    icon: null,
    nav: null,
    content: null,
    hero: null,
    page: null,
    card: null,
    form: null,
    lead: null,
    signal: null,
  },
  effect: {
    heroGradient: null,
    panelGradient: null,
    shadow: null,
    perspective: null,
    blur: null,
  },
});

/** Applies Signal's dark market-intelligence theme to the application root. */
export const themeClass = createTheme(vars, {
  color: {
    canvas: "#090b12",
    surface: "#11141e",
    surfaceRaised: "#171b29",
    input: "#0b0e16",
    text: "#edf2ff",
    ink: "#11151b",
    muted: "#929ab0",
    accent: "#c7ff49",
    danger: "#ff9e9e",
    border: "rgba(255, 255, 255, 0.1)",
    borderStrong: "rgba(255, 255, 255, 0.2)",
    overlay: "#101521d9",
  },
  font: { sans: '"Manrope", Arial, sans-serif', mono: '"DM Mono", monospace' },
  fontSize: {
    xs: "11px",
    sm: "12px",
    body: "13px",
    base: "14px",
    medium: "16px",
    large: "17px",
    display: "30px",
    score: "68px",
  },
  fontWeight: { medium: "500", bold: "700", extraBold: "800" },
  lineHeight: { tight: ".96", body: "1.55", relaxed: "1.7" },
  letterSpacing: {
    label: ".12em",
    title: "-.07em",
    card: "-.025em",
    brand: "-1px",
  },
  radius: { sm: "9px", md: "10px", lg: "16px", xl: "20px", pill: "28px" },
  space: {
    xxs: "7px",
    xs: "8px",
    sm: "11px",
    md: "16px",
    lg: "20px",
    xl: "32px",
    xxl: "54px",
  },
  size: {
    icon: "34px",
    nav: "76px",
    content: "1180px",
    hero: "480px",
    page: "75vh",
    card: "214px",
    form: "430px",
    lead: "540px",
    signal: "400px",
  },
  effect: {
    heroGradient: "linear-gradient(135deg, #354574, #131827 60%, #a2d72b)",
    panelGradient: "linear-gradient(135deg, #131a2d, #11141e 65%)",
    shadow: "drop-shadow(0 35px 45px #0009)",
    perspective: "perspective(800px) rotateY(-12deg) rotateX(6deg)",
    blur: "blur(8px)",
  },
});
